name: Update Pie Chart

on:
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora
  workflow_dispatch:  # Permite execução manual

jobs:
  update-pie-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats and Pie Chart
        run: |
          # Criar diretório caso não exista (opcional, caso queira salvar em pasta)
          mkdir -p ./stats  
          
          # Gerar estatísticas gerais
          curl -o ./stats/github-readme-stats.svg "https://github-readme-stats.vercel.app/api?username=jeffthedeveloper&show_icons=true&include_all_commits=true&count_private=true&cache_seconds=1800"

          # Gerar gráfico de pizza
          curl -o ./stats/github-readme-stats-pie.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=jeffthedeveloper&layout=pie&langs_count=10&theme=dracula&count_private=true&include_all_commits=true&v=2"

      - name: Validate SVG Files
        run: |
          for file in ./stats/*.svg; do
            if grep -i "error" "$file"; then
              echo "Erro na geração do SVG: $file"
              cat "$file"
              exit 1
            fi
          done

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --exit-code ./stats/; then
            echo "No changes detected."
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "has_changes=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.has_changes == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git add ./stats/github-readme-stats.svg
          git add ./stats/github-readme-stats-pie.svg
          git commit -m "Update GitHub Stats & Pie Chart"
          
          # 🔽 INSIRA SEU TOKEN AQUI 🔽
          git push https://x-access-token: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@github.com/jeffthedeveloper/jeffthedeveloper.git
