name: Update README stats
on:
  schedule:
    - cron: '0 * * * *' # Executa a cada hora
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anuraghazra/github-readme-stats@v1
        with:
          username: jeffthedeveloper
          show_icons: true
          include_all_commits: true
      - uses: anuraghazra/github-readme-stats@v1
        with:
          username: jeffthedeveloper
          show_icons: true
          include_all_commits: true
          output_svg: ./github-readme-stats.svg
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
